syntax = "proto3";

package grpc_messenger;

message Empty {}

message Ack {
  bool success = 1;
  string message = 2;
}

message ChatMessage {
  string from = 1;
  string to = 2;
  enum Type {
    TEXT = 0;
    FILE_START = 1;
    FILE_CHUNK = 2;
    FILE_END = 3;
    CONNECT = 4;
  }
  Type type = 3;
  string text = 4;
  string file_name = 5;
  int64 file_size = 6;
  bytes file_chunk = 7;
  int32 chunk_id = 8;
  int32 total_chunks = 9;
}

message FileChunk {
  bytes data = 1;
}

service ChatService {
  rpc ChatStream(stream ChatMessage) returns (stream ChatMessage);
  rpc Ping(Empty) returns (Empty);
  rpc UploadFile(stream FileChunk) returns (Ack);
}
