// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chat.proto

#include "chat.pb.h"
#include "chat.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace grpc_messenger {

static const char* ChatService_method_names[] = {
  "/grpc_messenger.ChatService/ChatStream",
  "/grpc_messenger.ChatService/Ping",
  "/grpc_messenger.ChatService/UploadFile",
};

std::unique_ptr< ChatService::Stub> ChatService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ChatService::Stub> stub(new ChatService::Stub(channel, options));
  return stub;
}

ChatService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ChatStream_(ChatService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_Ping_(ChatService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UploadFile_(ChatService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::grpc_messenger::ChatMessage, ::grpc_messenger::ChatMessage>* ChatService::Stub::ChatStreamRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::grpc_messenger::ChatMessage, ::grpc_messenger::ChatMessage>::Create(channel_.get(), rpcmethod_ChatStream_, context);
}

void ChatService::Stub::async::ChatStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::grpc_messenger::ChatMessage,::grpc_messenger::ChatMessage>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::grpc_messenger::ChatMessage,::grpc_messenger::ChatMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_ChatStream_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::grpc_messenger::ChatMessage, ::grpc_messenger::ChatMessage>* ChatService::Stub::AsyncChatStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::grpc_messenger::ChatMessage, ::grpc_messenger::ChatMessage>::Create(channel_.get(), cq, rpcmethod_ChatStream_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::grpc_messenger::ChatMessage, ::grpc_messenger::ChatMessage>* ChatService::Stub::PrepareAsyncChatStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::grpc_messenger::ChatMessage, ::grpc_messenger::ChatMessage>::Create(channel_.get(), cq, rpcmethod_ChatStream_, context, false, nullptr);
}

::grpc::Status ChatService::Stub::Ping(::grpc::ClientContext* context, const ::grpc_messenger::Empty& request, ::grpc_messenger::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::grpc_messenger::Empty, ::grpc_messenger::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ping_, context, request, response);
}

void ChatService::Stub::async::Ping(::grpc::ClientContext* context, const ::grpc_messenger::Empty* request, ::grpc_messenger::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::grpc_messenger::Empty, ::grpc_messenger::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void ChatService::Stub::async::Ping(::grpc::ClientContext* context, const ::grpc_messenger::Empty* request, ::grpc_messenger::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::grpc_messenger::Empty>* ChatService::Stub::PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::grpc_messenger::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::grpc_messenger::Empty, ::grpc_messenger::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ping_, context, request);
}

::grpc::ClientAsyncResponseReader< ::grpc_messenger::Empty>* ChatService::Stub::AsyncPingRaw(::grpc::ClientContext* context, const ::grpc_messenger::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPingRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientWriter< ::grpc_messenger::FileChunk>* ChatService::Stub::UploadFileRaw(::grpc::ClientContext* context, ::grpc_messenger::Ack* response) {
  return ::grpc::internal::ClientWriterFactory< ::grpc_messenger::FileChunk>::Create(channel_.get(), rpcmethod_UploadFile_, context, response);
}

void ChatService::Stub::async::UploadFile(::grpc::ClientContext* context, ::grpc_messenger::Ack* response, ::grpc::ClientWriteReactor< ::grpc_messenger::FileChunk>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::grpc_messenger::FileChunk>::Create(stub_->channel_.get(), stub_->rpcmethod_UploadFile_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::grpc_messenger::FileChunk>* ChatService::Stub::AsyncUploadFileRaw(::grpc::ClientContext* context, ::grpc_messenger::Ack* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::grpc_messenger::FileChunk>::Create(channel_.get(), cq, rpcmethod_UploadFile_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::grpc_messenger::FileChunk>* ChatService::Stub::PrepareAsyncUploadFileRaw(::grpc::ClientContext* context, ::grpc_messenger::Ack* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::grpc_messenger::FileChunk>::Create(channel_.get(), cq, rpcmethod_UploadFile_, context, response, false, nullptr);
}

ChatService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< ChatService::Service, ::grpc_messenger::ChatMessage, ::grpc_messenger::ChatMessage>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::grpc_messenger::ChatMessage,
             ::grpc_messenger::ChatMessage>* stream) {
               return service->ChatStream(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::grpc_messenger::Empty, ::grpc_messenger::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::grpc_messenger::Empty* req,
             ::grpc_messenger::Empty* resp) {
               return service->Ping(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[2],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< ChatService::Service, ::grpc_messenger::FileChunk, ::grpc_messenger::Ack>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::grpc_messenger::FileChunk>* reader,
             ::grpc_messenger::Ack* resp) {
               return service->UploadFile(ctx, reader, resp);
             }, this)));
}

ChatService::Service::~Service() {
}

::grpc::Status ChatService::Service::ChatStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::grpc_messenger::ChatMessage, ::grpc_messenger::ChatMessage>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::Ping(::grpc::ServerContext* context, const ::grpc_messenger::Empty* request, ::grpc_messenger::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::UploadFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::grpc_messenger::FileChunk>* reader, ::grpc_messenger::Ack* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace grpc_messenger

