apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger-app
spec:
  selector:
    matchLabels:
      app: messenger
  template:
    metadata:
      labels:
        app: messenger
    spec:
      containers:
        - name: messenger
          image: messenger-app:latest
          imagePullPolicy: Never  # Используйте локальный образ
          ports:
            - containerPort: 9090