apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: messenger-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: messenger
  endpoints:
  - port: http
    interval: 15s
    path: /metrics