apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-scaler
  template:
    metadata:
      labels:
        app: ml-scaler
    spec:
      serviceAccountName: ml-scaler-sa
      containers:
      - name: ml-scaler
        image: ml-scaler-image:latest
        imagePullPolicy: Never  
        env:
        - name: PROMETHEUS_URL
          value: "http://prometheus-server.default.svc:80"